apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}"
spec:
  terminationGracePeriodSeconds: 10
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo Running; sleep 50"]
      lifecycle:
        preStop:
          exec:
            command: ["sleep", "10"]
